spring:
  datasource:
    url: jdbc:h2:mem:local
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org.hibernate.type: trace
